const path = require("path");
const merge = require("webpack-merge");
const webpackNodeExternals = require("webpack-node-externals");

const commonConfig = require("./webpack.common");

const serverConfig = {
  // Inform webpack that we're building a bundle
  // for nodeJS, rather than for the browser
  // This will affect the behaviour of webpack
  target: "node",

  // Tell webpack the root file
  // of our server application
  entry: "./src/index.js",

  // Tell webpack where to put the output file
  // that gets generated. i.e Where to place
  // the bundle.js

  // __dirname -> Reference to current working directory
  // The build folder gets generated by webpack when it runs
  output: {
    filename: "bundle.js",
    path: path.resolve(__dirname, "build")
  },
  // Ensure that we don't import an entire library into our server bundle.js
  externals: [webpackNodeExternals()]
};

module.exports = merge(commonConfig, serverConfig);
