const path = require("path");
const merge = require("webpack-merge");

const commonConfig = require("./webpack.common");

const clientConfig = {
  // Tell webpack the root file(entry point)
  // of our client application
  entry: "./src/client/client.js",

  // Tell webpack where to put the output file
  // that gets generated. i.e Where to place
  // the bundle.js

  // __dirname -> Reference to current working directory
  // The build folder gets generated by webpack when it runs
  output: {
    filename: "bundle.js",
    path: path.resolve(__dirname, "public")
  }
};

module.exports = merge(commonConfig, clientConfig);
